/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Ave: typeof import('./src/components/ave.vue')['default']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    HeaderNavbar: typeof import('./src/components/HeaderNavbar.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyledText: typeof import('./src/components/StyledText.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
    WaveItem: typeof import('./src/components/WaveItem.vue')['default']
    'ㅈave': typeof import('./src/components/ㅈave.vue')['default']
  }
}
