/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    CodeBlockItem: typeof import('./src/components/block/CodeBlockItem.vue')['default']
    FileBlockItem: typeof import('./src/components/block/FileBlockItem.vue')['default']
    HeaderNavbar: typeof import('./src/components/HeaderNavbar.vue')['default']
    NotionBlock: typeof import('./src/components/block/NotionBlock.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RichTextRenderer: typeof import('./src/components/RichTextRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyledText: typeof import('./src/components/StyledText.vue')['default']
    TableBlockItem: typeof import('./src/components/block/TableBlockItem.vue')['default']
    TextBlockItem: typeof import('./src/components/block/TextBlockItem.vue')['default']
    UrlBlockItem: typeof import('./src/components/block/UrlBlockItem.vue')['default']
    WaveItem: typeof import('./src/components/WaveItem.vue')['default']
  }
}
